//! The real generator behind the five bundled non-Jerry-Dark theme files, and the parity tests
//! that keep them honest.

use crate::settings::custom_theme::{CustomTheme, CustomThemeFile};
use crate::theme;

/// One bundled theme's real, pinned identity - the exact `name`/`subtitle` it has always had, the
/// file it lives in, and the five `[background, panel, green-ish, amber-ish, blue-ish]` swatches
/// it was originally defined by (transcribed verbatim from the pre-rewrite
/// `assets/themes/*.toml` files, which held exactly these five values and nothing else).
pub struct BuiltinThemeSource {
    pub name: &'static str,
    pub subtitle: &'static str,
    pub file_name: &'static str,
    pub swatches: [u32; 5],
}

/// The six bundled themes, in the exact order `crate::settings::state::THEME_DEFS` lists them
/// (index `0` is Jerry Dark, the real default).
pub const BUILTIN_THEME_SOURCES: [BuiltinThemeSource; 6] = [
    BuiltinThemeSource {
        name: "Jerry Dark",
        subtitle: "default",
        file_name: "jerry-dark.toml",
        swatches: [0x0e0f11, 0x1a1e21, 0x5cb87f, 0xe2a336, 0x74ade8],
    },
    BuiltinThemeSource {
        name: "Jerry Dim",
        subtitle: "lower contrast",
        file_name: "jerry-dim.toml",
        swatches: [0x15181b, 0x20252a, 0x6ab97f, 0xd8a94a, 0x7f9ad4],
    },
    BuiltinThemeSource {
        name: "Slate",
        subtitle: "cool greys",
        file_name: "slate.toml",
        swatches: [0x0d1117, 0x161b22, 0x57a773, 0xc9a227, 0x6b9bd1],
    },
    BuiltinThemeSource {
        name: "Ember",
        subtitle: "warm",
        file_name: "ember.toml",
        swatches: [0x12100e, 0x1e1a16, 0x8fae6b, 0xd98b3a, 0xc4713f],
    },
    BuiltinThemeSource {
        name: "Moss",
        subtitle: "green-tinted",
        file_name: "moss.toml",
        swatches: [0x0f1310, 0x1a201b, 0x7fc79a, 0xc8b45a, 0x6f9bb5],
    },
    BuiltinThemeSource {
        name: "Paper",
        subtitle: "light \u{b7} beta",
        file_name: "paper.toml",
        swatches: [0xf4f1ea, 0xe4e0d6, 0x3f7a52, 0xa8752a, 0x3d6c9c],
    },
];

/// Jerry Dark's own swatches - the base every derivation is measured against (see
/// [`crate::theme::derive_shift`]).
pub fn jerry_dark_swatches() -> [u32; 5] {
    BUILTIN_THEME_SOURCES[0].swatches
}

/// Builds a real, complete, writable theme file from a derived palette - the one shared shape both
/// the built-in generator below and the Themes page's "Generate from colour" action produce, so
/// the two can never emit differently-structured files.
pub fn generated_theme_file(
    name: &str,
    subtitle: &str,
    preview: [u32; 5],
    palette: Vec<(&'static str, gpui::Rgba)>,
) -> CustomThemeFile {
    CustomTheme {
        name: name.to_string(),
        subtitle: subtitle.to_string(),
        base: Some("Jerry Dark".to_string()),
        preview: Some(preview),
        overrides: palette.into_iter().collect(),
        source_path: None,
    }
    .to_file()
}

/// The real TOML text for one bundled theme's `assets/themes/*.toml` file, header comment
/// included.
#[allow(clippy::expect_used)] // a generated theme file must be valid by construction
pub fn generate_builtin_theme_toml(source: &BuiltinThemeSource) -> String {
    let is_jerry_dark = source.swatches == jerry_dark_swatches();
    let file = if is_jerry_dark {
        CustomTheme {
            name: source.name.to_string(),
            subtitle: source.subtitle.to_string(),
            base: None,
            preview: Some(source.swatches),
            overrides: std::collections::HashMap::new(),
            source_path: None,
        }
        .to_file()
    } else {
        let shift = theme::derive_shift(jerry_dark_swatches(), source.swatches);
        generated_theme_file(
            source.name,
            source.subtitle,
            source.swatches,
            theme::derived_palette(shift),
        )
    };

    let header = if is_jerry_dark {
        "# Jerry Dark - this app's default theme, and the base every other theme inherits from.\n\
         #\n\
         # This file deliberately names no colours: every one of Jerry Dark's ~270 values is the\n\
         # compiled-in default of the matching token, so restating them here would just be a\n\
         # second copy to keep in sync. Copy any other bundled theme instead if you want a full\n\
         # palette to start from.\n\
         #\n\
         # Generated by `crate::settings::builtin_themes` - see that module's docs to regenerate."
            .to_string()
    } else {
        format!(
            "# {} - a bundled Jerry theme, and a worked example of the theme file format.\n\
             #\n\
             # GENERATED FILE. Every colour below was derived from Jerry Dark's own palette by the\n\
             # HSL transform in `crate::theme::derive_shift`, using this theme's five original\n\
             # swatches ({}), then written out literally - so it renders\n\
             # exactly as this theme always has while being an ordinary, hand-editable theme file\n\
             # with no special status.\n\
             #\n\
             # Regenerate with `crate::settings::builtin_themes` - see that module's docs.",
            source.name,
            source
                .swatches
                .iter()
                .map(|value| format!("#{value:06x}"))
                .collect::<Vec<_>>()
                .join(", "),
        )
    };
    crate::settings::theme_file_format::write_theme_toml(
        &file
            .validate_with_builtin_check(false)
            .expect("a generated theme file must be valid by construction")
            .to_file(),
        &header,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::settings::custom_theme::parse_theme_file_str;
    use crate::settings::state::THEME_DEFS;

    /// The real, checked-in bytes of each bundled theme file, in [`BUILTIN_THEME_SOURCES`] order -
    /// embedded exactly the way `crate::settings::state::THEME_DEFS` embeds them, so these tests
    /// check the same bytes the app actually ships with.
    const CHECKED_IN: [&str; 6] = [
        include_str!("../../../../assets/themes/jerry-dark.toml"),
        include_str!("../../../../assets/themes/jerry-dim.toml"),
        include_str!("../../../../assets/themes/slate.toml"),
        include_str!("../../../../assets/themes/ember.toml"),
        include_str!("../../../../assets/themes/moss.toml"),
        include_str!("../../../../assets/themes/paper.toml"),
    ];

    #[test]
    fn regenerate_builtin_theme_files_when_asked() {
        if std::env::var("JERRY_REGENERATE_THEMES").as_deref() != Ok("1") {
            return;
        }
        let assets = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../assets/themes")
            .canonicalize()
            .expect("the real assets/themes directory must exist");
        for source in &BUILTIN_THEME_SOURCES {
            let path = assets.join(source.file_name);
            std::fs::write(&path, generate_builtin_theme_toml(source))
                .unwrap_or_else(|err| panic!("failed to write {}: {err}", path.display()));
            println!("wrote {}", path.display());
        }
    }

    #[test]
    fn every_checked_in_builtin_theme_file_matches_the_generator() {
        for (source, checked_in) in BUILTIN_THEME_SOURCES.iter().zip(CHECKED_IN.iter()) {
            assert_eq!(
                generate_builtin_theme_toml(source),
                *checked_in,
                "assets/themes/{} is out of date - regenerate it (see this module's docs)",
                source.file_name
            );
        }
    }

    #[test]
    fn every_builtin_theme_resolves_exactly_what_the_generator_produces() {
        use crate::settings::custom_theme::compile_palette_by_name;

        for source in BUILTIN_THEME_SOURCES.iter().skip(1) {
            let palette = compile_palette_by_name(source.name, &[])
                .expect("a bundled theme must compile")
                .expect("a bundled non-Jerry-Dark theme has real overrides");
            let shift = theme::derive_shift(jerry_dark_swatches(), source.swatches);
            let generated: std::collections::HashMap<&str, gpui::Rgba> =
                theme::derived_palette(shift).into_iter().collect();

            for token in theme::all_tokens() {
                let expected = crate::settings::custom_theme::rgba_to_hex(
                    *generated
                        .get(token.key)
                        .expect("derived_palette covers every registered token"),
                );
                let actual = crate::settings::custom_theme::rgba_to_hex(
                    *palette
                        .get(token.key)
                        .unwrap_or_else(|| panic!("{} is missing from {}", token.key, source.name)),
                );
                assert_eq!(
                    expected, actual,
                    "{}: {} resolves to #{actual:06x}, but the generator produces #{expected:06x} \
                     - regenerate the bundled files (see this module's docs)",
                    source.name, token.key
                );
            }
        }
    }

    #[test]
    fn every_bundled_theme_file_clears_its_syntax_contrast_floors() {
        use crate::settings::custom_theme::compile_palette_by_name;

        for source in BUILTIN_THEME_SOURCES.iter() {
            let palette = compile_palette_by_name(source.name, &[])
                .expect("a bundled theme must compile")
                .unwrap_or_default();
            let resolve = |key: &str| {
                palette.get(key).copied().unwrap_or_else(|| {
                    theme::token_for_key(key)
                        .expect("a real registered key")
                        .default
                })
            };
            let background = resolve("surface.center");
            for token in theme::all_tokens() {
                let Some(floor) = theme::syntax_contrast_floor_for_test(token.key) else {
                    continue;
                };
                let ratio = theme::contrast_ratio(resolve(token.key), background);
                assert!(
                    ratio >= floor,
                    "{}: {} is {ratio:.2}:1 against the editor background, below its {floor}:1 \
                     floor",
                    source.name,
                    token.key
                );
            }
        }
    }

    #[test]
    fn jerry_dark_is_still_a_real_identity_with_no_overrides_at_all() {
        let jerry_dark = parse_builtin(0);
        assert!(jerry_dark.overrides.is_empty());
        assert_eq!(jerry_dark.preview_swatches(), jerry_dark_swatches());
    }

    fn parse_builtin(index: usize) -> CustomTheme {
        let text = CHECKED_IN[index];
        let file = CustomThemeFile::from_toml_str(text).expect("must parse");
        file.validate_with_builtin_check(false)
            .expect("must validate")
    }

    #[test]
    fn every_bundled_file_is_an_ordinary_theme_file_a_user_could_have_written() {
        for (index, source) in BUILTIN_THEME_SOURCES.iter().enumerate() {
            let renamed = CHECKED_IN[index].replace(
                &format!("name = \"{}\"", source.name),
                "name = \"Renamed For Test\"",
            );
            let theme = parse_theme_file_str(&renamed).unwrap_or_else(|err| {
                panic!("{} should parse as a user file: {err}", source.file_name)
            });
            assert_eq!(theme.name, "Renamed For Test");
        }
    }

    #[test]
    fn every_bundled_theme_is_a_genuinely_different_palette() {
        let windows: Vec<u32> = THEME_DEFS
            .iter()
            .map(|def| crate::settings::custom_theme::rgba_to_hex(def.theme.window_background()))
            .collect();
        let mut unique = windows.clone();
        unique.sort_unstable();
        unique.dedup();
        assert_eq!(
            unique.len(),
            windows.len(),
            "two bundled themes share a window background: {windows:02x?}"
        );
    }

    #[test]
    fn every_bundled_theme_paints_its_own_readable_terminal() {
        use crate::settings::custom_theme::compile_palette_by_name;

        let mut backgrounds: Vec<u32> = Vec::new();
        for source in BUILTIN_THEME_SOURCES.iter() {
            let palette = compile_palette_by_name(source.name, &[])
                .expect("a bundled theme must compile")
                .unwrap_or_default();
            let resolve =
                |token: theme::ColorToken| palette.get(token.key).copied().unwrap_or(token.default);
            let background = resolve(theme::terminal::BACKGROUND);
            let foreground = resolve(theme::terminal::FOREGROUND);

            let ratio = theme::contrast_ratio(foreground, background);
            assert!(
                ratio >= 4.5,
                "{}: terminal.foreground is {ratio:.2}:1 against terminal.background - unstyled \
                 terminal output would be hard to read",
                source.name
            );

            // The pane is painted *into* `surface.pty`; a terminal fill that drifted away from it
            // would put the exact lighter-rectangle-inside-the-app back that issue #208 is about.
            assert_eq!(
                crate::settings::custom_theme::rgba_to_hex(background),
                crate::settings::custom_theme::rgba_to_hex(resolve(theme::surface::PTY)),
                "{}: the terminal fill has drifted off the surface it is painted into",
                source.name
            );

            backgrounds.push(crate::settings::custom_theme::rgba_to_hex(background));
        }

        let mut unique = backgrounds.clone();
        unique.sort_unstable();
        unique.dedup();
        assert_eq!(
            unique.len(),
            backgrounds.len(),
            "two bundled themes paint the terminal the same colour, so switching between them \
             would not visibly change it: {backgrounds:06x?}"
        );
    }

    #[test]
    fn paper_really_generates_a_light_window_background_and_the_rest_stay_dark() {
        for def in THEME_DEFS.iter() {
            let is_light = theme::theme_is_light(def.theme.window_background());
            assert_eq!(
                is_light,
                def.name == "Paper",
                "{} should{} be a light theme",
                def.name,
                if def.name == "Paper" { "" } else { " not" }
            );
        }
    }
}
